### ISSUE TITLE
problems with installation and "GPU not found"

### ISSUE THREAD

**Issue by markopetek** [amorehead/alphafold_non_docker#1]
First, I run into a few problems with the installation that I was able to resolve:

1) The run_alphafold.py requires --use_gpu_relax flag
ERROR: `flag --use_gpu_relax=None: Flag --use_gpu_relax must have a value other than None.`

fix: adding the parameter to python commands in the sh script:
(this issue was also reported in this blog: https://programs.team/alphafold-installation-non-docker-image.html )

```
if [[ "$db_preset" == "reduced_dbs" && "$model_preset" == "monomer" ]]; then
  $(python $alphafold_script --use_gpu_relax --hhblits_binary_path=$hhblits_binary_path --hhsearch_binary_path=$hhsearch_binary_path --jackhmmer_binary_path=$jackhmmer_binary_path --kalign_binary_path=$kalign_binary_path --small_bfd_database_path=$small_bfd_database_path --mgnify_database_path=$mgnify_database_path --template_mmcif_dir=$template_mmcif_dir --obsolete_pdbs_path=$obsolete_pdbs_path --pdb70_database_path=$pdb70_database_path --uniref90_database_path=$uniref90_database_path --data_dir=$data_dir --output_dir=$output_dir --fasta_paths=$fasta_path --max_template_date=$max_template_date --model_preset=$model_preset --db_preset=$db_preset --benchmark=$benchmark --use_precomputed_msas=$use_precomputed_msas --remove_msas_after_use=$remove_msas_after_use --logtostderr)
elif [[ "$db_preset" == "reduced_dbs" ]]; then
  $(python $alphafold_script --use_gpu_relax --hhblits_binary_path=$hhblits_binary_path --hhsearch_binary_path=$hhsearch_binary_path --jackhmmer_binary_path=$jackhmmer_binary_path --kalign_binary_path=$kalign_binary_path --small_bfd_database_path=$small_bfd_database_path --mgnify_database_path=$mgnify_database_path --template_mmcif_dir=$template_mmcif_dir --obsolete_pdbs_path=$obsolete_pdbs_path --pdb_seqres_database_path=$pdb_seqres_database_path --uniprot_database_path=$uniprot_database_path --uniref90_database_path=$uniref90_database_path --data_dir=$data_dir --output_dir=$output_dir --fasta_paths=$fasta_path --max_template_date=$max_template_date --model_preset=$model_preset --db_preset=$db_preset --benchmark=$benchmark --use_precomputed_msas=$use_precomputed_msas --remove_msas_after_use=$remove_msas_after_use --logtostderr --is_prokaryote_list=$is_prokaryote)
elif [[ "$db_preset" == "full_dbs" && "$model_preset" == "monomer" ]]; then
  $(python $alphafold_script --use_gpu_relax --hhblits_binary_path=$hhblits_binary_path --hhsearch_binary_path=$hhsearch_binary_path --jackhmmer_binary_path=$jackhmmer_binary_path --kalign_binary_path=$kalign_binary_path --bfd_database_path=$bfd_database_path --mgnify_database_path=$mgnify_database_path --template_mmcif_dir=$template_mmcif_dir --obsolete_pdbs_path=$obsolete_pdbs_path --pdb70_database_path=$pdb70_database_path --uniclust30_database_path=$uniclust30_database_path --uniref90_database_path=$uniref90_database_path --data_dir=$data_dir --output_dir=$output_dir --fasta_paths=$fasta_path --max_template_date=$max_template_date --model_preset=$model_preset --db_preset=$db_preset --benchmark=$benchmark --use_precomputed_msas=$use_precomputed_msas --remove_msas_after_use=$remove_msas_after_use --logtostderr)
else
  $(python $alphafold_script --use_gpu_relax --hhblits_binary_path=$hhblits_binary_path --hhsearch_binary_path=$hhsearch_binary_path --jackhmmer_binary_path=$jackhmmer_binary_path --kalign_binary_path=$kalign_binary_path --bfd_database_path=$bfd_database_path --mgnify_database_path=$mgnify_database_path --template_mmcif_dir=$template_mmcif_dir --obsolete_pdbs_path=$obsolete_pdbs_path --pdb_seqres_database_path=$pdb_seqres_database_path --uniclust30_database_path=$uniclust30_database_path --uniprot_database_path=$uniprot_database_path --uniref90_database_path=$uniref90_database_path --data_dir=$data_dir --output_dir=$output_dir --fasta_paths=$fasta_path --max_template_date=$max_template_date --model_preset=$model_preset --db_preset=$db_preset --benchmark=$benchmark --use_precomputed_msas=$use_precomputed_msas --remove_msas_after_use=$remove_msas_after_use --logtostderr --is_prokaryote_list=$is_prokaryote)
fi
```

2) ERROR: mgy_clusters.fa not found
fix: rename mgnify database file to mgy_clusters.fa (deleted the date at the end)

**3) ERROR: unable to initialize backend 'gpu': not_found
This one I was not able to resolve.**

alphafold reverts to CPU but this is much slower. 

The `nvidia-smi` command gives a normal output and other software that uses GPU is able to find it:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000     On   | 00000000:27:00.0 Off |                  N/A |
| 30%   49C    P8    10W / 125W |      3MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by markopetek** [comment]
Checking other non-docker alphafold installation instructions on Github (https://github.com/kalininalab/alphafold_non_docker) I found this command that fixed my GPU issue (run in conda env):

`pip install --upgrade jax==0.2.14 jaxlib==0.1.69+cuda111 -f https://storage.googleapis.com/jax-releases/jax_releases.html`
